services:
  - type: web
    name: altiq
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn altiq_site.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: NODE_VERSION
        value: "18"
      - key: DEBUG
        value: "False"
      - key: ALTIQ_ENV
        value: "main"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: altiq-db
          property: connectionString

databases:
  - name: altiq-db
    plan: free
    region: oregon

